# This is an auto-generated Django model module created by ogrinspect.
from django.contrib.gis.db import models

class RoadNW(models.Model):
    idnw = models.FloatField()
    feattyp = models.IntegerField()
    ft = models.IntegerField()
    f_jnctid = models.FloatField()
    f_jncttyp = models.IntegerField()
    t_jnctid = models.FloatField()
    t_jncttyp = models.IntegerField()
    pj = models.IntegerField()
    meters = models.FloatField()
    frc = models.IntegerField()
    netclass = models.IntegerField()
    netbclass = models.IntegerField()
    net2class = models.IntegerField()
    name = models.CharField(max_length=100)
    namelc = models.CharField(max_length=3)
    sol = models.IntegerField()
    nametyp = models.IntegerField()
    charge = models.CharField(max_length=2)
    shieldnum = models.CharField(max_length=50)
    rtetyp = models.IntegerField()
    rtedir = models.CharField(max_length=2)
    rtedirvd = models.CharField(max_length=2)
    procstat = models.IntegerField()
    fow = models.IntegerField()
    sliprd = models.IntegerField()
    freeway = models.IntegerField()
    backrd = models.IntegerField()
    tollrd = models.IntegerField()
    rdcond = models.IntegerField()
    stubble = models.IntegerField()
    privaterd = models.IntegerField()
    constatus = models.CharField(max_length=2)
    oneway = models.CharField(max_length=2)
    f_bp = models.IntegerField()
    t_bp = models.IntegerField()
    f_elev = models.IntegerField()
    t_elev = models.IntegerField()
    kph = models.IntegerField()
    minutes = models.FloatField()
    posaccur = models.IntegerField()
    carriage = models.CharField(max_length=1)
    lanes = models.IntegerField()
    ramp = models.IntegerField()
    ada = models.IntegerField()
    trans = models.IntegerField()
    dynspeed = models.IntegerField()
    speedcat = models.IntegerField()
    nthrutraf = models.IntegerField()
    roughrd = models.IntegerField()
    partstruc = models.IntegerField()
    geom = models.LineStringField(srid=4326)

# Auto-generated `LayerMapping` dictionary for RoadNW model
roadnw_mapping = {
    'idnw' : 'ID',
    'feattyp' : 'FEATTYP',
    'ft' : 'FT',
    'f_jnctid' : 'F_JNCTID',
    'f_jncttyp' : 'F_JNCTTYP',
    't_jnctid' : 'T_JNCTID',
    't_jncttyp' : 'T_JNCTTYP',
    'pj' : 'PJ',
    'meters' : 'METERS',
    'frc' : 'FRC',
    'netclass' : 'NETCLASS',
    'netbclass' : 'NETBCLASS',
    'net2class' : 'NET2CLASS',
    'name' : 'NAME',
    'namelc' : 'NAMELC',
    'sol' : 'SOL',
    'nametyp' : 'NAMETYP',
    'charge' : 'CHARGE',
    'shieldnum' : 'SHIELDNUM',
    'rtetyp' : 'RTETYP',
    'rtedir' : 'RTEDIR',
    'rtedirvd' : 'RTEDIRVD',
    'procstat' : 'PROCSTAT',
    'fow' : 'FOW',
    'sliprd' : 'SLIPRD',
    'freeway' : 'FREEWAY',
    'backrd' : 'BACKRD',
    'tollrd' : 'TOLLRD',
    'rdcond' : 'RDCOND',
    'stubble' : 'STUBBLE',
    'privaterd' : 'PRIVATERD',
    'constatus' : 'CONSTATUS',
    'oneway' : 'ONEWAY',
    'f_bp' : 'F_BP',
    't_bp' : 'T_BP',
    'f_elev' : 'F_ELEV',
    't_elev' : 'T_ELEV',
    'kph' : 'KPH',
    'minutes' : 'MINUTES',
    'posaccur' : 'POSACCUR',
    'carriage' : 'CARRIAGE',
    'lanes' : 'LANES',
    'ramp' : 'RAMP',
    'ada' : 'ADA',
    'trans' : 'TRANS',
    'dynspeed' : 'DYNSPEED',
    'speedcat' : 'SPEEDCAT',
    'nthrutraf' : 'NTHRUTRAF',
    'roughrd' : 'ROUGHRD',
    'partstruc' : 'PARTSTRUC',
    'geom' : 'LINESTRING',
}
